### ISSUE TITLE
unable to create a react doc

### ISSUE THREAD

**Issue by bujidao** [MuYunyun/create-react-doc#157]
when i typed `npx create-react-doc doc` and then run in my cmd.

for a while, it appears 
```
E:\******\react-doc>npx create-react-doc doc
Downloading Chromium r686378 - 143 Mb [====================] 100% 0.0s
Cannot read property 'domain' of null
```

then i enter my file, i fond nothing.

i wanner to know how to use `create-react-doc`

thinks

**Comment by MuYunyun** [comment]
@bujidao Thanks, it's a bug, I'll fix it this week. If you need it in a hurry, you can fork [blog](https://github.com/MuYunyun/blog) to use.

**Comment by MuYunyun** [comment]
@bujidao hi, the problem has been fixed. You can try `npx create-react-doc doc` again with the version of create-react-doc 1.3.4
