### ISSUE TITLE
.menu-item li height made scrollbar

### ISSUE THREAD

**Issue by fh345392977** [MuYunyun/create-react-doc#17]
![image](https://user-images.githubusercontent.com/16329330/87114547-71078f00-c2a3-11ea-8a09-2422003af1e4.png)
![image](https://user-images.githubusercontent.com/16329330/87114654-aca25900-c2a3-11ea-850c-1a878b8567d3.png)

这个`height`属性导致有滚动条出现，去掉这个后，滚动条消失，发现高度变成了`40.84`。
继续深入发现是
![image](https://user-images.githubusercontent.com/16329330/87114848-32260900-c2a4-11ea-9444-462e923509e7.png)
这里的`vertical-align: middle;`导致的

**Comment by MuYunyun** [comment]
感谢指出。

这里 vertical-align: middle 的作用是让 icon 和文字水平对齐, 因此也不能去掉。可以在 submenu 或者 menu 处加个 `overflow: hidden`

我在下个版本带上。

**Comment by MuYunyun** [comment]
@fh345392977  0.1.20 version 已修复
