### ISSUE TITLE
Menu search

### ISSUE THREAD

**Issue by fh345392977** [MuYunyun/create-react-doc#18]
左侧菜单的搜索可以提上日程吗？

**Comment by MuYunyun** [comment]
👌, 在 [RFC v1](https://github.com/MuYunyun/create-react-doc/issues/2) 中是有支持全局搜索的计划的。会在后续陆续支持。

**Comment by MuYunyun** [comment]
* 已支持全局菜单 + 内容搜索 @fh345392977 
  * 效果: ![image](https://user-images.githubusercontent.com/19354791/89115832-6b2a5580-d4bf-11ea-9475-c31abdeaa766.png)
  * [mr](https://github.com/MuYunyun/create-react-doc/pull/22)
