### ISSUE TITLE
Error's with create-react-doc

### ISSUE THREAD

**Issue by Icearcticfox** [MuYunyun/create-react-doc#180]
Hi, i'm try install with npm/npx, but i get the same error's:
```
~$ npm init react-doc doc
Downloading Chromium r686378 - 114 Mb [====================] 100% 0.0s 
 ❎ crd-templates install fail.
```
```
~$ npx create-react-doc doc
Downloading Chromium r686378 - 114 Mb [====================] 100% 0.0s 
 ❎ crd-templates install fail.
```
how i can fix it?

**Comment by MuYunyun** [comment]
@Icearcticfox Hi, I try `npx create-react-doc doc` in my local env, it seems ok in this step. Maybe you can retry because of the network problem...
![image](https://user-images.githubusercontent.com/19354791/134621032-763a7e5b-7417-4c95-ac9e-8e055a976925.png)

**Comment by Icearcticfox** [comment]
ye, it's mine problem, and i fixed. Thank you =)
