### ISSUE TITLE
无法初始化

### ISSUE THREAD

**Issue by ace7chan** [MuYunyun/create-react-doc#61]
执行
`npx create-react-doc doc`
`npm init create-react-doc doc`
`yarn create create-react-doc doc`
任意一条，都会报安装超时的错误；根据`https://github.com/yarnpkg/yarn/issues/4890`的几个方案也不行（win平台）

**Comment by ace7chan** [comment]
换镜像之后可行，但是在部署到github page的时候遇到另一个问题：
```
Run actions/setup-node@v2.1.0
  with:
    node-version: 12.x
    always-auth: false
    check-latest: false
    token: ***
Found in cache @ C:\hostedtoolcache\windows\node\12.20.0\x64
Error: Unable to process command '::add-path::C:\hostedtoolcache\windows\node\12.20.0\x64' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by MuYunyun** [comment]
> https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

这个问题我这里没遇到过。可以看下 actions/setup-node 这个 github-action 的一些配置项。

如果自动发版不行的话, 可以临时先采取[手动发版](http://muyunyun.cn/create-react-doc/#/%E7%AB%99%E7%82%B9%E5%8F%91%E5%B8%83)。

**Comment by MuYunyun** [comment]
> 换镜像之后可行，但是在部署到github page的时候遇到另一个问题：
> 
> ```
> Run actions/setup-node@v2.1.0
>   with:
>     node-version: 12.x
>     always-auth: false
>     check-latest: false
>     token: ***
> Found in cache @ C:\hostedtoolcache\windows\node\12.20.0\x64
> Error: Unable to process command '::add-path::C:\hostedtoolcache\windows\node\12.20.0\x64' successfully.
> Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> ```

这个问题我这里没遇到过。可以看下 actions/setup-node 这个 github-action 的一些配置项。

如果自动发版不行的话, 可以临时先采取[手动发版](http://muyunyun.cn/create-react-doc/#/%E7%AB%99%E7%82%B9%E5%8F%91%E5%B8%83)。

**Comment by ace7chan** [comment]
发布后显示的是类似：https://acecoooool.github.io/notebook/
