### ISSUE TITLE
界面只显示README.md的主页

### ISSUE THREAD

**Issue by AceCoooool** [MuYunyun/create-react-doc#62]
按照步骤，最后打开的页面：https://acecoooool.github.io/notebook/ 如此处所示，没有显示左侧边栏的情况（本都yarn start则没有问题），请问这种情况该如何解决呢~ 谢谢

**Comment by MuYunyun** [comment]
可以检查一下根目录的 config.yml 文件里的 menu 字段, 检查下是否与项目文件大小写匹配。
![image](https://user-images.githubusercontent.com/19354791/103251838-8c7f6700-49b5-11eb-9834-a4248f2358c6.png)

**Comment by AceCoooool** [comment]
这部分一致的; 在yarn start显示是没有问题的；  打开你的网页看到的都是xxx/#/xxx，但是我这边都是直接xxx/xxx，少了这个#；

**Comment by MuYunyun** [comment]
了解了。可以见 [站点发布](http://muyunyun.cn/create-react-doc/#/%E7%AB%99%E7%82%B9%E5%8F%91%E5%B8%83) 第一次部署的 case。需要在 setting 中进行设置项目采用分支。

**Comment by AceCoooool** [comment]
非常感谢~是我没有仔细看~感谢感谢
