### ISSUE TITLE
Feature Request: support mathjax

### ISSUE THREAD

**Issue by AceCoooool** [MuYunyun/create-react-doc#63]
您好，请问如何添加对mathjax的支持呢

**Comment by MuYunyun** [comment]
> 您好，请问如何添加对mathjax的支持呢

个人没使用过 mathjax, 可以补充一下使用的背景吗?

**Comment by AceCoooool** [comment]
markdown里面的数学公式，在网页上显示不了

发自我的iPhone

**Comment by MuYunyun** [comment]
@AceCoooool 了解了, 我看了下 https://github.com/mathjax/MathJax, 这星期比较忙, 过了这星期我想想看如何暴露出插件的口子使用它, 或者提供一个配置选项在组件内部集成它(如果体积不是很大的话)。

**Comment by AceCoooool** [comment]
截图上传还是不太方便，很多场景数学公式还是很频繁的。如果方便的话，还是希望后续能添加这个功能（个人没有接触前端方面的知识，处理起来可能比较头疼）~谢谢作者

**Comment by MuYunyun** [comment]
恩, 好的。后续有进度同步你。

**Comment by MuYunyun** [comment]
@AceCoooool 升级 create-react-doc 到 0.2.21 版本

![image](https://user-images.githubusercontent.com/19354791/104115377-dec36f00-5349-11eb-9b99-b6875d26b701.png)

[文档: 高阶用法](http://muyunyun.cn/create-react-doc/#/%E9%AB%98%E9%98%B6%E7%94%A8%E6%B3%95)

![image](https://user-images.githubusercontent.com/19354791/104115404-16cab200-534a-11eb-8829-621b5a82f5e4.png)

**Comment by AceCoooool** [comment]
非常感谢！

**Comment by MuYunyun** [comment]
@AceCoooool 

在 create-react-doc 1.3 版本中可以在 markdown 中直接书写 latex 数学公式(不用像之前那样作额外配置了)。
[数学公式](http://muyunyun.cn/create-react-doc/%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F)
