### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/create-create-react-doc: Not found".

### ISSUE THREAD

**Issue by mercurywang** [MuYunyun/create-react-doc#67]
Was I the only one having this issue? 😰

```
yarn create create-react-doc doc
yarn create v1.22.10
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/create-create-react-doc: Not found".
```

If there is any responses, I would be super appreciated. 
P.S. (Mac OS)

**Comment by MuYunyun** [comment]
@mercurywang
It's my writing fault. You can try `yarn create react-doc doc` instead of `yarn create create-react-doc doc`.

> [yarn create](https://classic.yarnpkg.com/en/docs/cli/create/)

**Comment by mercurywang** [comment]
Bravo, that works! Thanks! 🥳

**Comment by MuYunyun** [comment]
> Bravo, that works! Thanks! 🥳

fine. I close it.
